# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  clamav:
    image: clamav/clamav
    extra_hosts:
      - "host.docker.internal:host-gateway"
  filedb:
    image: mongo
    extra_hosts:
      - "host.docker.internal:host-gateway"
  file:
    image: file
    build:
      context: .
      dockerfile: File/Dockerfile
    ports:
      - 5000:5000
    extra_hosts:
      - "host.docker.internal:host-gateway"
volumes:
    clam_data:
    mongo_data: